"""add mora_generada field to cuota

Revision ID: 019a1c7790fc
Revises: 3053b6dad6e3
Create Date: 2025-12-08 22:43:11.683837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '019a1c7790fc'
down_revision = '3053b6dad6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear el tipo ENUM si no existe
    op.execute("CREATE TYPE mediopagoenum AS ENUM ('EFECTIVO', 'TARJETA_DEBITO', 'TARJETA_CREDITO', 'TRANSFERENCIA', 'BILLETERA_ELECTRONICA', 'PAGO_AUTOMATICO')")
    
    with op.batch_alter_table('cuotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mora_generada', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    # Eliminar el server_default después de agregar la columna
    with op.batch_alter_table('cuotas', schema=None) as batch_op:
        batch_op.alter_column('mora_generada', server_default=None)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_mora', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('medio_pago', sa.Enum('EFECTIVO', 'TARJETA_DEBITO', 'TARJETA_CREDITO', 'TRANSFERENCIA', 'BILLETERA_ELECTRONICA', 'PAGO_AUTOMATICO', name='mediopagoenum'), nullable=False, server_default='EFECTIVO'))
        batch_op.drop_constraint('uq_cuota_fecha_pago', type_='unique')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('estado')

    # Eliminar server_defaults de pagos
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('monto_mora', server_default=None)
        batch_op.alter_column('medio_pago', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', postgresql.ENUM('PENDIENTE', 'REALIZADO', 'DEVUELTO', name='estadopagoenum'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('uq_cuota_fecha_pago', ['cuota_id', 'fecha_pago'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('medio_pago')
        batch_op.drop_column('monto_mora')

    with op.batch_alter_table('cuotas', schema=None) as batch_op:
        batch_op.drop_column('mora_generada')

    # ### end Alembic commands ###
