"""fix: add atribute email on Cliente model

Revision ID: 1cf38e205110
Revises: d180242c41a9
Create Date: 2025-10-15 17:58:47.942263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf38e205110'
down_revision = 'd180242c41a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_electronico', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('correo_electronico')

    # ### end Alembic commands ###
