"""agregar campos mora y saldo pendiente a cuotas

Revision ID: 3053b6dad6e3
Revises: add_pago_table
Create Date: 2025-12-08 13:11:08.891946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3053b6dad6e3'
down_revision = 'add_pago_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mora_acumulada', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('saldo_pendiente', sa.Numeric(precision=12, scale=2), nullable=False))

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index('ix_pagos_cuota_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index('ix_pagos_cuota_id', ['cuota_id'], unique=False)

    with op.batch_alter_table('cuotas', schema=None) as batch_op:
        batch_op.drop_column('saldo_pendiente')
        batch_op.drop_column('mora_acumulada')

    # ### end Alembic commands ###
