"""Add Usuario model for authentication

Revision ID: 59d23688588f
Revises: 019a1c7790fc
Create Date: 2025-12-10 04:53:01.699077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59d23688588f'
down_revision = '019a1c7790fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_ultima_conexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('monto_contable',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_comment='Deuda contable de la cuota')
        batch_op.alter_column('ajuste_redondeo',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Pérdida/Ganancia por redondeo',
               existing_comment='Pérdida/Ganancia por redondeo (Ley N° 29571)',
               existing_nullable=False)
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', postgresql.ENUM('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', name='metodopagoenum'), autoincrement=False, nullable=False))
        batch_op.alter_column('ajuste_redondeo',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Pérdida/Ganancia por redondeo (Ley N° 29571)',
               existing_comment='Pérdida/Ganancia por redondeo',
               existing_nullable=False)
        batch_op.alter_column('monto_contable',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_comment='Deuda contable de la cuota')

    op.drop_table('usuarios')
    # ### end Alembic commands ###
