"""add_pago_table

Revision ID: add_pago_table
Revises: 1cf38e205110
Create Date: 2024-12-07 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_pago_table'
down_revision = '1cf38e205110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear tabla pagos
    op.create_table(
        'pagos',
        sa.Column('pago_id', sa.Integer(), nullable=False),
        sa.Column('cuota_id', sa.Integer(), nullable=False),
        sa.Column('monto_pagado', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('fecha_pago', sa.Date(), nullable=False),
        sa.Column('fecha_registro', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('estado', sa.Enum('PENDIENTE', 'REALIZADO', 'DEVUELTO', name='estadopagoenum'), nullable=False),
        sa.Column('comprobante_referencia', sa.String(length=100), nullable=True),
        sa.Column('observaciones', sa.Text(), nullable=True),
        sa.CheckConstraint('monto_pagado > 0', name='chk_monto_pagado_positivo'),
        sa.ForeignKeyConstraint(['cuota_id'], ['cuotas.cuota_id'], ),
        sa.PrimaryKeyConstraint('pago_id'),
        sa.UniqueConstraint('cuota_id', 'fecha_pago', name='uq_cuota_fecha_pago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar tabla pagos
    op.drop_table('pagos')
    
    # Eliminar enum
    op.execute('DROP TYPE IF EXISTS estadopagoenum')
    # ### end Alembic commands ###
