"""initial migration

Revision ID: d180242c41a9
Revises: 
Create Date: 2025-10-13 01:49:41.246352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd180242c41a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('pep', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('cliente_id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('declaraciones_juradas',
    sa.Column('declaracion_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_declaracion', sa.Enum('USO_PROPIO', 'PEP', 'AMBOS', name='tipodeclaracionenum'), nullable=False),
    sa.Column('fecha_firma', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('firmado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.PrimaryKeyConstraint('declaracion_id')
    )
    op.create_table('prestamos',
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interes_tea', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=False),
    sa.Column('f_otorgamiento', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('f_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.Enum('VIGENTE', 'CANCELADO', name='estadoprestamoenum'), nullable=False),
    sa.Column('requiere_dec_jurada', sa.Boolean(), nullable=False),
    sa.Column('declaracion_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(requiere_dec_jurada = FALSE) OR (declaracion_id IS NOT NULL)', name='chk_declaracion_si_requerida'),
    sa.CheckConstraint('interes_tea >= 0 AND interes_tea <= 100', name='chk_interes_tea_rango'),
    sa.CheckConstraint('monto_total > 0', name='chk_monto_total_positivo'),
    sa.CheckConstraint('plazo > 0', name='chk_plazo_positivo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['declaracion_id'], ['declaraciones_juradas.declaracion_id'], ),
    sa.PrimaryKeyConstraint('prestamo_id')
    )
    op.create_table('cuotas',
    sa.Column('cuota_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('monto_cuota', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_interes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('monto_pagado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('monto_cuota > 0', name='chk_monto_cuota_positivo'),
    sa.CheckConstraint('numero_cuota > 0', name='chk_numero_cuota_positivo'),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.prestamo_id'], ),
    sa.PrimaryKeyConstraint('cuota_id'),
    sa.UniqueConstraint('prestamo_id', 'numero_cuota', name='uq_prestamo_numero_cuota')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuotas')
    op.drop_table('prestamos')
    op.drop_table('declaraciones_juradas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
