"""empty message

Revision ID: d946ab8ccbcd
Revises: 019a1c7790fc
Create Date: 2025-12-09 03:45:34.391105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd946ab8ccbcd'
down_revision = '019a1c7790fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', name='metodopagoenum'), nullable=False))
        batch_op.add_column(sa.Column('monto_contable', sa.Numeric(precision=12, scale=2), nullable=False, comment='Deuda contable de la cuota'))
        batch_op.add_column(sa.Column('ajuste_redondeo', sa.Numeric(precision=12, scale=2), nullable=False, comment='Pérdida/Ganancia por redondeo (Ley N° 29571)'))
        batch_op.alter_column('monto_pagado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Monto recibido en caja',
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_cuota_fecha_pago', ['cuota_id', 'fecha_pago'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cuota_fecha_pago', type_='unique')
        batch_op.alter_column('monto_pagado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Monto recibido en caja',
               existing_nullable=False)
        batch_op.drop_column('ajuste_redondeo')
        batch_op.drop_column('monto_contable')
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###
